sudo: required
services:
  - docker

#env:
#  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - docker network create bnet
#  - docker-compose up -d
  - docker build -t cloudurable/docker-bridge-nats -f cicd/Dockerfile_nats.dev .
  - docker build -t cloudurable/docker-bridge-ibmmq -f cicd/Dockerfile_ibmmq.dev .
  - docker build -t cloudurable/docker-bridge-artemis -f cicd/Dockerfile_artemismq.dev .
  - docker build -t cloudurable/docker-nats-bridge -f cicd/Dockerfile_bridge2.dev .

#  - docker run -d gilmarmacieljr/docker-bridge-nats
#  - docker run -d gilmarmacieljr/docker-bridge-ibmmq
#  - docker run -d gilmarmacieljr/docker-bridge-artemis
#  - docker ps


script:
  - docker run --net bnet --name nats-server -d cloudurable/docker-bridge-nats
  - docker run --net bnet --name artemis-server -d cloudurable/docker-bridge-artemis
  - docker run --net bnet --name ibm-server -d cloudurable/docker-bridge-ibmmq
  - docker run --net bnet --name bridge cloudurable/docker-nats-bridge
#  - docker run -d gilmarmacieljr/docker-bridge
#  - NATS_BRIDGE_JMS_USER=cloudurable NATS_BRIDGE_JMS_PWD=cloudurable NATS_BRIDGE_NATS_SERVERS=nats://nats-server:4222 NATS_BRIDGE_JMS_CONNECTION_FACTORY=tcp://active-mq:61616 ./gradlew clean test
#  - exit
#  - docker ps
#  - docker run gilmarmacieljr/docker-bridge npm run test -- --coverage

after_script:
#  - docker-compose down
  - docker rm -f $(docker ps -aq)
  - docker network remove bnet
#  - docker stop gilmarmacieljr/docker-bridge-nats
#  - docker stop gilmarmacieljr/docker-bridge-ibmmq
