---
name: "Starter Config"
dateTime:
  - 2020
  - 4
  - 30
  - 0
  - 53
  - 50
  - 423615000
bridges:
  - name: "natsForwardToJMS"
    bridgeType: "FORWARD"
    transforms: ["addHeader"]
    source:
      name: "natsSrc"
      busType: "NATS"
      subject: "forward-subject"
      clusterName: "natsCluster"
    destination:
      name: "ibmMQDst"
      busType: "JMS"
      subject: "DEV.QUEUE.2"
      clusterName: "ibmMqCluster"
    copyHeaders: false
    workers: 3
    tasks : 1
  - name: "natsToIBMMq"
    bridgeType: "REQUEST_REPLY"
    source:
      name: "nats"
      busType: "NATS"
      subject: "b-subject"
      clusterName: "natsCluster"
    destination:
      name: "ibmMQ"
      busType: "JMS"
      subject: "DEV.QUEUE.1"
      clusterName: "ibmMqCluster"
    copyHeaders: false
    workers: 4
    tasks : 1
clusters:
  jmsCluster:
    name: "jmsCluster"
    properties: !<jms>
      config:
        java.naming.factory.initial: "org.apache.activemq.artemis.jndi.ActiveMQInitialContextFactory"
        connectionFactory.ConnectionFactory: "tcp://localhost:61616"
        queue.queue/testQueue: "queue.queue/testQueue=testQueue"
      userName: "cloudurable"
      password: "cloudurable"
      jmsDestinationType: "QUEUE"
      autoConfig: "ACTIVE_MQ"
  natsCluster:
    name: "natsCluster"
    properties: !<nats>
      host: "localhost"
      port: 4222
      servers: []
      config:
        io.nats.client.reconnect.wait: "3000"
        io.nats.client.reconnect.max: "10"
        io.nats.client.timeout: "4000"
        io.nats.client.tls.jssl.enable: "true"
        io.nats.client.tls.truststore.path: "../certs/truststore.jks"
        io.nats.client.tls.keystore.path: "../certs/keystore.jks"
        io.nats.client.tls.algorithm: "SunX509"
        io.nats.client.tls.keystore.password: "cloudurable1"
        io.nats.client.tls.truststore.password: "cloudurable2"
  ibmMqCluster:
    name: "ibmMqCluster"
    properties: !<jms>
      config:
        java.naming.factory.initial: "io.nats.bridge.integration.ibmmq.IbmMqInitialContextFactory"
        nats.ibm.mq.host: "tcp://localhost:1414"
        nats.ibm.mq.channel: "DEV.APP.SVRCONN"
        nats.ibm.mq.queueManager: "QM1"
        nats.ibm.mq.queueModelName: "DEV.MODEL"
        nats.ibm.mq.queueModelPrefix: "DEV*"
      userName: "app"
      password: "passw0rd"
      jmsDestinationType: "QUEUE"
      autoConfig: "IBM_MQ"