# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./message
    - name: Build Messages / Tranfrom Lib with Gradle
      run: ./gradlew clean build publishToMavenLocal -x test
      working-directory: ./message
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./core
    - name: Build Core Bridge Lib with Gradle
      run: ./gradlew clean build publishToMavenLocal -x test
      working-directory: ./core
    - name: Build Bridge Admin Server with Gradle
      run: ./gradlew clean distZip
      working-directory: ./admin
